### PR TITLE
Handle more Return Types in Client

### PR DESCRIPTION
**Pull request by LaurenceWarne**
Hi, this PR is a proposed fix for https://github.com/alcarney/lsp-devtools/issues/9, though I've also added support for all return  types for the currently implemented request types.

In full the new types handled are:

- `client.completion_request` handles `null` and `CompletionItem[]` response types in addition to `CompletionList`

- `client.definition_request` handles the `null` response type in addition to `Location`, `LocationLink[]` and `Location[]`

- `client.document_link_request` handles the `null` response type in addition to `DocumentLink[]`

- `client.document_symbols_request `handles null and `SymbolInformation[]` response types in addition to `DocumentSymbol[]`

- `client.hover_request` handles the null response type in addition to `Hover`

Return type has also been added to each of the method docstrings, happy to change this if you don't like the style.

In terms of testing, I've been running the local branch for a bunch of my integration tests and it looks good, though there are some I haven't implemented :sweat_smile:.

Thanks, let me know what you think!

### CODE REVIEW

**Comment by alcarney** [comment]
This looks great! Thanks for this :smile:

**Comment by LaurenceWarne** [comment]
Thanks, any chance of you having time to cut a new release soon :slightly_smiling_face: ?

**Comment by alcarney** [comment]
`v0.1.0` is now out! I'd wanted to make sure #5 made it in first since it's been open long enough :smile:

**Comment by LaurenceWarne** [comment]
Great, thanks!

**Pull request merged**
